handlers:
  - url: /favicon.ico
    static_files: /assets/favicon.ico
    upload: /assets/favicon.ico
runtime: nodejs18
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

